package me.licheng.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK.
 */
public class Book {

    private Long id;
    /** Not-null value. */
    private String text;
    private String comment;
    private Boolean islogin;
    private Float accountmoney;
    private java.util.Date date;

    public Book() {
    }

    public Book(Long id) {
        this.id = id;
    }

    public Book(Long id, String text, String comment, Boolean islogin, Float accountmoney, java.util.Date date) {
        this.id = id;
        this.text = text;
        this.comment = comment;
        this.islogin = islogin;
        this.accountmoney = accountmoney;
        this.date = date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getText() {
        return text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setText(String text) {
        this.text = text;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public Boolean getIslogin() {
        return islogin;
    }

    public void setIslogin(Boolean islogin) {
        this.islogin = islogin;
    }

    public Float getAccountmoney() {
        return accountmoney;
    }

    public void setAccountmoney(Float accountmoney) {
        this.accountmoney = accountmoney;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
